id="0001"
url="https://lukesmith.xyz/articles/obvious-technical-solutions"
title="The hardest technical solutions are right in front of your face."
author="Luke Smith"
type="article"
createdAt="2022-07-14T14:46:24+02:00"
