id="0003"
url="https://www.youtube.com/watch?v=lgnMyF-o0sQ"
title="The Origin of Consciousness in the Breakdown of the Bicameral Mind"
author="Luke Smith"
type="video"
createdAt="2021-01-15T20:00:00+01:00"
