id="0004"
url="https://lukesmith.xyz/articles/modern-freedom-means-being-a-slave-to-impulses/"
title="Modern \"Freedom\" Means Being a Slave to Impulses"
author="Luke Smith"
type="article"
createdAt="2022-07-14T15:05:08+02:00"
