"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](color_orange)\
[▓](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$nodejs\
$terraform\
[](fg:color_blue bg:color_bg3)\
$docker_context\
[](fg:color_bg3 bg:color_bg1)\
$aws\
[](fg:color_bg1)\
$line_break$character
"""

right_format = """
$cmd_duration\
[ ](fg:color_bg1)\
$status\
"""

add_newline = false
palette = 'gruvbox_dark'

# A continuation prompt that displays two filled in arrows
continuation_prompt = '▶▶ '

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[status]
format = '[$symbol $status](red) '
map_symbol = true
disabled = false
symbol = "✘"
not_found_symbol = ""
sigint_symbol = "󰣪"

[cmd_duration]
min_time = 10
format = "[$duration](yellow)"

[aws]
symbol = "󰸏"
style = "bg:color_bg1 fg:color_fg0"
format = "[$symbol$profile ]($style)"

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Notes" = "󰧑 "
"Videos" = " "
"Work" = " "

[git_branch]
symbol = ""
style = "fg:color_fg0 bg:color_aqua"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:color_fg0 bg:color_aqua"
format = "[($all_status$ahead_behind)]($style)"

[nodejs]
symbol = "󰎙"
style = "fg:color_fg0 bg:color_blue"
format = "[ $symbol( $version)]($style)"

[terraform]
symbol = ""
style = "fg:color_fg0 bg:color_blue"
format = "[ $symbol( $version@$workspace)]($style)"
detect_files = [".terraform-version"]

[docker_context]
symbol = ""
style = "fg:#83a598 bg:color_bg3"
format = "[ $symbol( $context) ]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
