services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: llm-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    ports:
      - "5432:5432"
    volumes:
      - ./.local/volumes/n8n_db_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: llm-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    depends_on:
      - postgres
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=llm-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - TZ=Europe/Amsterdam
      # Optional environment variables:
      # - N8N_ENCRYPTION_KEY=your_encryption_key
      # - N8N_HOST=your-domain.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      # - WEBHOOK_TUNNEL_URL=https://your-domain.com
    volumes:
      - ./.local/volumes/n8n_app_data:/home/node/.n8n

  # scrapper-api:
  #   image: node:latest
  #   cpus: 4
  #   container_name: llm-scrapper-api
  #   # dont start it automatically
  #   restart: "no"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - n8n
  #   environment:
  #     - DB_HOST=llm-postgres
  #     - DB_PORT=5432
  #     - DB_DATABASE=scrapper_prod
  #     - DB_USER=n8n
  #     - DB_PASSWORD=n8n
  #   volumes:
  #     - ~/Work/deckr41/mono/packages/public/@api_scrapper:/home/node/app
  #   command: bash -c "cd /home/node/app && npm install && npm start"

  openui:
    image: ghcr.io/wandb/openui:latest
    container_name: llm-openui
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./.local/volumes/openui_data:/app/data

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: llm-open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./.local/volumes/open-webui:/app/backend/data
